# Generated by Django 5.0.6 on 2025-01-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HSeg8comp_01', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_02', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_03', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_04', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_05', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_06', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_07', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_08', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_09', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_10', models.CharField(blank=True, max_length=100, null=True)),
                ('HSeg8comp_11', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
