# Generated by Django 5.0.6 on 2025-01-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapahorario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapa',
            name='horario',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
