# Generated by Django 5.0.6 on 2024-08-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=20)),
                ('email_aluno', models.CharField(max_length=50)),
                ('fone_aluno', models.CharField(max_length=20)),
                ('nasc_aluno', models.DateField(null=True)),
            ],
        ),
    ]
