# Generated by Django 5.0.6 on 2024-08-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='email_aluno',
            field=models.EmailField(max_length=50),
        ),
    ]
