# Generated by Django 5.0.6 on 2024-08-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_matricula_email_aluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='email_aluno',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='nasc_aluno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
