# Generated by Django 5.0.6 on 2025-01-21 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_matricula_email_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='data_pre',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
