# Generated by Django 5.0 on 2024-01-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_cliente_dias_curso_cliente_duracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_vencimento', models.CharField(max_length=50)),
                ('valor_mensalidade', models.CharField(max_length=50)),
                ('descricao_pagamento', models.CharField(max_length=50)),
                ('data_pagamento', models.CharField(max_length=50)),
                ('valor_pago', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
