# Generated by Django 5.0.6 on 2024-06-04 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(null=True)),
                ('valor_mensalidade', models.CharField(max_length=20)),
                ('descricao_pagamento', models.CharField(max_length=50)),
                ('data_pagamento', models.DateField(null=True)),
                ('valor_com_juros', models.CharField(max_length=20)),
                ('valor_pago', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
