# Generated by Django 5.0 on 2024-01-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
