# Generated by Django 5.0 on 2024-01-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_financeiro_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeiro',
            name='titulo',
        ),
    ]
