# Generated by Django 5.0 on 2024-01-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_remove_financeiro_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
    ]
