# Generated by Django 5.0 on 2024-01-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_financeiro_data_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='valor_com_juros',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data_vencimento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_mensalidade',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='valor_pago',
            field=models.CharField(max_length=20),
        ),
    ]
