# Generated by Django 5.0.6 on 2024-06-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_datanascimento_delete_carro'),
        ('financeiro', '0005_financeiro_valor_com_juros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
            preserve_default=False,
        ),
    ]
