# Generated by Django 5.0 on 2024-01-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_categoriamanutencao_servico_categoria_manutencao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='cliente',
            new_name='nome',
        ),
    ]
