# Generated by Django 5.0 on 2024-01-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_rename_cliente_servico_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='nome',
            new_name='cliente',
        ),
    ]
