# Generated by Django 5.0 on 2023-12-17 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=12)),
                ('data_nascimento', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('nome_responsavel', models.CharField(max_length=50)),
                ('cpf_responsavel', models.CharField(max_length=12)),
                ('nascimento_responsavel', models.CharField(max_length=50)),
                ('telefone_responsavel', models.CharField(max_length=50)),
                ('cursos', models.CharField(max_length=50)),
                ('inicio', models.CharField(max_length=50)),
                ('mensalidade', models.CharField(max_length=50)),
                ('parcelas', models.IntegerField(max_length=2)),
                ('dia_pagamento', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('lavagens', models.IntegerField(default=0)),
                ('consertos', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
