# Generated by Django 5.0.6 on 2024-06-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=12)),
                ('datanascimento', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=40)),
                ('cep', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('nome_responsavel', models.CharField(max_length=50)),
                ('cpf_responsavel', models.CharField(max_length=12)),
                ('nascimento_responsavel', models.DateField(null=True)),
                ('telefone_responsavel', models.CharField(max_length=50)),
                ('cursos', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
                ('inicio', models.DateField(null=True)),
                ('dias_curso', models.CharField(max_length=50)),
                ('horarios_curso', models.CharField(max_length=50)),
                ('instrutor', models.CharField(max_length=50)),
                ('mensalidade', models.CharField(max_length=50)),
                ('parcelas', models.CharField(max_length=2)),
                ('dia_pagamento', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
            ],
        ),
    ]
