# Generated by Django 5.0.6 on 2024-06-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='datanascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
