# Generated by Django 5.0 on 2023-12-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='parcelas',
            field=models.CharField(max_length=2),
        ),
    ]
