# Generated by Django 5.0.6 on 2024-06-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento_responsavel',
            field=models.DateField(blank=True, null=True),
        ),
    ]
