# Generated by Django 5.0 on 2023-12-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_parcelas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_nascimento',
            new_name='datanascimento',
        ),
    ]
