# Generated by Django 5.0.6 on 2024-06-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='total',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
