# Generated by Django 5.0 on 2023-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_data_nascimento_cliente_datanascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_curso',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='duracao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='horarios_curso',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='instrutor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
