# Generated by Django 5.0.6 on 2024-06-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_dias_curso_cliente_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='datanascimento',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
