# Generated by Django 5.0.6 on 2024-06-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='situacao',
            field=models.CharField(default='Cursando', max_length=50),
        ),
    ]
