# Generated by Django 5.0.6 on 2024-06-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='situacao',
            field=models.CharField(max_length=50),
        ),
    ]
