# Generated by Django 5.0.6 on 2024-06-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_data_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_matricula',
            field=models.DateTimeField(),
        ),
    ]
