# Generated by Django 5.0.6 on 2025-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_cliente_data_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='valor_material',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
